### ISSUE TITLE
jquery wrap() function triggers error “document.createDocumentFragment is not a function” on dynamic content load (when using migrate)

### ISSUE THREAD

**Issue by ekonoval** [jquery/jquery-migrate#178] opened 2016-04-25 16:01 UTC
Recently I've encountered a very strange behavior of wrap() method of jquery. I have a banner system and another site which uses that system. I try to update jquery version to the latest available one of the 1x branch. But I use some old plugins and would like them working with migrate fallback.

Spending a lot of hours I defined that dynamic content loading by document.write affects the work of wrap() which triggers very strange error

> TypeError: document.createDocumentFragment is not a function safeFrag = document.createDocumentFragment();

I had a few experiments with isolated code and defined that **wrap() works fine when I don't use migrate fallback** or don't use content loading by document.write.

I have no ideas why it's working this way, maybe somebody can help me? I set up a few examples

1) Expected to see "WRAPPING DONE" https://jsfiddle.net/quadroval/w0czwvbj/

`$(function() {
  $('#tryToWrap').wrap("<p>WRAPPING DONE</p>")
});`
2) Static content - wrapping works fine https://jsfiddle.net/quadroval/jLfygsgr/

3) Migration is turned off - wrapping works fine too. The content is loaded dynamically https://jsfiddle.net/quadroval/x89y0ka2/

Here you can see clear example http://sunsey.0fees.net/exper/dynamic.html

**Comment by dmethvin** [comment] 2016-04-27 14:46
The problem is the setting of `document.context=\'fHA6Mw==\';` in the code which triggers some logic inside Migrate. We can work around that but I am wondering why it is set?

Also, the `.wrap()` call isn't valid, it's trying to wrap a paragraph around a div. Paragraphs can't contain block-level elements. That's not causing the error though.

**Comment by ekonoval** [comment] 2016-04-27 14:54
well I use some old banner system openx v2.8.8 , and it generates the code like I put to jsfiddle. I also have some plugin CoinSlider [js](http://internet-bilet.ua/-js/coin-slider.js)  which uses some kind of wrap, which fails. I just simplified the code to see what exactly is causing the trouble. Strange thing that without migrate everything works fine. So I thought it may be related to migration issue. Before that I've been using jquery 1.8 and everything worked fine too.

**Comment by ekonoval** [comment] 2016-04-27 15:01
the code of coinSlider where error occurs http://prntscr.com/axifz0

> 		init = function(el){
				
			order[el.id] 		= new Array();	// order of square appereance
			images[el.id]		= new Array();
			links[el.id]		= new Array();
			linksTarget[el.id]	= new Array();
			titles[el.id]		= new Array();
			imagePos[el.id]		= 0;
			squarePos[el.id]	= 0;
			reverse[el.id]		= 1;						
				
			params[el.id] = $.extend({}, $.fn.coinslider.defaults, options);
						
			// create images, links and titles arrays
			$.each($('#'+el.id+' img'), function(i,item){
				images[el.id][i] 		= $(item).attr('src');
				links[el.id][i] 		= $(item).parent().is('a') ? $(item).parent().attr('href') : '';
				linksTarget[el.id][i] 	= $(item).parent().is('a') ? $(item).parent().attr('target') : '';
				titles[el.id][i] 		= $(item).next().is('span') ? $(item).next().html() : '';
				$(item).hide();
				$(item).next().hide();
			});			
			

			// set panel
			$(el).css({
				'background-image':'url('+images[el.id][0]+')',
				'width': params[el.id].width,
				'height': params[el.id].height,
				'position': 'relative',
				'background-position': 'top left'
			});
			//.wrap("<div class='coin-slider' id='coin-slider-"+el.id+"' />"); //todo removed as it caused TypeError: a.createDocumentFragment is not a function
			
				
			// create title bar
			$('#'+el.id).append("<div class='cs-title' id='cs-title-"+el.id+"' style='position: absolute; bottom:0; left: 0; z-index: 100;'></div>");
						
			$.setFields(el);

			if(params[el.id].navigation)
				$.setNavigation(el);
			
			$.transition(el,0);
			$.transitionCall(el);
				
		}

**Comment by dmethvin** [comment] 2016-04-29 01:03
@ekonoval Can you verify that the test case here fixes the problem for you? The build of Migrate there has the patch in #183 and I'll do another 1.x release soon to include it. Thanks for the info!

https://jsfiddle.net/w0czwvbj/5/

**Comment by ekonoval** [comment] 2016-04-29 05:55
@dmethvin thank you very much, it's working fine now!

**Comment by dmethvin** [comment] 2016-04-29 19:06
Landed in 1.x at c09b6a01435e4b5c16e12f2476ea8456e4a7985f, release coming next week.

**Closed by dmethvin** 2016-04-29 19:06 UTC
