### ISSUE TITLE
Allow file excludes

### ISSUE THREAD

**Issue by mnbeer** [jquery/jquery-migrate#278] opened 2017-12-18 23:13 UTC
The console can get littered with warnings and errors from a 3rd-party or in-house plugin, items that need to be addressed but might have to wait. Would be really great if one could specify a list of files to exclude from logging so one could concentrate on the immediate code-base at hand.

**Comment by mgol** [comment] 2017-12-19 08:56
The problem is that those warnings come from Migrate which doesn't know where a particular call came from. We'd have to generate & look at the stack trace at every warning to determine where it came from and the stack trace format is not standardized... This looks like a big can of worms.

**Comment by mnbeer** [comment] 2017-12-20 00:13
If it is not worth it, I understand. The stack trace would definitely have to be examined. I assumed that since the stack trace and its file names are so clearly printed, that examining file names wouldn't be a big deal.  There would definitely be an upside. Imagine a web app with hundreds of pages that are dependent on jQuery UI.  jQuery-Migrate spews out deprecation warnings that must be waded through and ignored each time.

**Comment by dmethvin** [comment] 2017-12-20 00:59
If you (or someone else) wants to propose some specific way to do this, we could discuss and someone (not the core team) could create a PR. It's likely to be a lot of work and since it requires the user to configure things it is unlikely to be that appealing to most devs. We still recommend Migrate only as a diagnostic tool and when it's used that way you're not looking at the messages for very long.

I would prefer that when people find issues with third-party jQuery plugins or libraries being reported by Migrate, they file a PR against them to fix the issue. That will actually solve the problem (and solve it for everyone) rather than just ignoring it in Migrate.

I'll close the issue but feel free to discuss a design here if you're interested; we can reopen if it looks like it could work.

**Closed by dmethvin** 2017-12-20 00:59 UTC
