### ISSUE TITLE
migrate file listed is not minimized

### ISSUE THREAD

**Issue by Critter** [jquery/jquery-migrate#306] opened 2018-07-10 21:03 UTC
This file:[jquery-migrate-3.0.1.min.js](https://code.jquery.com/jquery-migrate-3.0.1.min.js) is not minimized.

The link is on [this](https://github.com/jquery/jquery-migrate) page.

**Comment by mgol** [comment] 2018-07-10 22:05
A duplicate of #300.

**Closed by mgol** 2018-07-10 22:05 UTC
