### ISSUE TITLE
3.0.1 min file is not fully minimized

### ISSUE THREAD

**Issue by Koi7** [jquery/jquery-migrate#315] opened 2019-01-23 12:02 UTC
https://code.jquery.com/jquery-migrate-3.0.1.min.js
check this file
it's just obfuscated, not minified

**Comment by mgol** [comment] 2019-01-23 12:54
A duplicate of #300. This is fixed, the next release will have a properly minified file.

Fortunately, the gzipped size didn't jump that much.

**Closed by mgol** 2019-01-23 12:54 UTC
