### ISSUE TITLE
"define cannot be used indirect" error after webpack build using jquery-migrate 3.0.1

### ISSUE THREAD

**Issue by doberkofler** [jquery/jquery-migrate#273] opened 2017-09-27 06:41 UTC
After upgrading the jquery-migrate npm package to version 3.0.1 in a webpack 3 build environment reports an exception: `define cannot be used indirect`! Reverting to version 3.0.0 solves the problem indicating that the problem has been caused the latest version of jquery-migrate.

**Comment by ldrick** [comment] 2017-09-27 09:48
Same here, had to go back to 3.0.0

**Comment by dmethvin** [comment] 2017-09-27 11:50
See also #272, which was the first report. Even though that wasn't much info, it's more than is being reported here which is just an error message. 

How are you loading jQuery Migrate? 

@Krinkle my guess is that f92c74340134de7263dc1d7e030eef74a9ca1f2e is the cause, people most likely have Webpack configs that are wrapping the old non-AMD Migrate module. 

@doberkofler @ldrick @k-funk Can you provide at least some scrap of detail about how you're loading Migrate? Is it mentioned in your Webpack config?

**Comment by ldrick** [comment] 2017-09-27 12:31
Hi, I have this in my main.ts:

```typescript
if (process.env.ENV !== "production") {
    // tell webpack to load jquery-migrate, no assignment needed
    // tslint:disable-next-line no-var-requires
    require("jquery-migrate");
}
```

Due to I am running with karma, this is the webpack-config used within my karma.conf.js

```javascript
const webpackConfig = {
    output: {
        libraryTarget: "window",
        libraryExport: "default",
    },
    resolve: {
        extensions: [".ts", ".js"],
    },
    plugins: [
        new webpack.SourceMapDevToolPlugin({
            filename: null,
            test: /\.(ts|js)($|\?)/i,
        }),
    ],
    module: {
        rules: [
            {
                loader: "ts-loader",
                test: /\.ts$/,
                exclude: /node_modules/,
                options: {
                    compilerOptions: {
                        declaration: false,
                    },
                },
            },
            {
                loader: "istanbul-instrumenter-loader",
                enforce: "post",
                test: /\.ts$/,
                exclude: /(node_modules|\.spec\.ts$)/,
                options: {
                    esModules: true,
                },
            },
        ],
    },
};
```

If you need more Information, I will try to provide anything, even if I'am sure, thats not the most common environment I am running, but many things depend on legacy code here.

**Comment by mgol** [comment] 2017-09-27 12:37
@dmethvin Perhaps we shouldn't have released that version as `3.0.1` but as `3.1.0` as it added a new feature in the form of UMD support which, as we see, breaks some people that were relying on this feature missing (we've already gotten a couple of those reports so it might be more widespread). 

If that is, indeed, the case, then maybe we should publish a quick `3.0.2` that would only revert f92c74340134de7263dc1d7e030eef74a9ca1f2e and then re-publish the current `3.0.1` as `3.1.0`? Though I'm not sure if that helps now that npm uses the `^` range when adding to the `package.json` by default.

@doberkofler @ldrick how are you installing jQuery Migrate? Could you both show your relevant `package.json` entry?

**Comment by ldrick** [comment] 2017-09-27 12:42
@mgol We are currently loading with strict version via npm.
```json
"devDependencies": {
...
"jquery-migrate": "3.0.0",
...
}
```

**Comment by dmethvin** [comment] 2017-09-27 12:43
@mgol I was thinking of the same resolution. I doubt it would make a difference as far as these reports are concerned because of the way it is being loaded and the version ranges in the package.json file.

**Comment by ievgenvarava** [comment] 2017-09-27 12:45
we use '~' range so releasing 3.0.2 with reverted changes would definitely help

`"jquery-migrate": "~3.0.0",`

https://github.com/spryker/Gui/blob/master/assets/Zed/package.json#L20

**Comment by mgol** [comment] 2017-09-27 12:51
@k-funk could you write you install jQuery Migrate as well? I assume a `package.json` entry so I'm interested in the version range you load.

**Comment by dmethvin** [comment] 2017-09-27 13:02
Oh also what version of Webpack?

**Comment by doberkofler** [comment] 2017-09-27 13:14
@dmethvin 

Some more information as requested:

environment:
- OS: Windows 7 x64
- node: 8.5.0
- webpack: 3.6.0

dependencies:
- "jquery": "3.2.1"
- "jquery-migrate": "3.0.0"

how are the modules loaded in webpack:
- jquery: 'expose-loader?$!expose-loader?jQuery!jquery'
- jquery-migrate: 'jquery-migrate/dist/jquery-migrate.js'

**Comment by doberkofler** [comment] 2017-09-27 13:16
@dmethvin I was also wondering, if there is a change log (I've missed reading) describing the changes in 3.0.1?

**Comment by dmethvin** [comment] 2017-09-27 13:39
@doberkofler No there is not but looking at https://github.com/jquery/jquery-migrate/commits/master the last release was July 2016 and there aren't too many commits to browse through. The AMD change was the first one landed after the 3.0.0 release.

**Comment by ldrick** [comment] 2017-09-27 13:45
I got this working by adding:
```javascript
const webpackConfig = {
    output: {
        libraryTarget: "window",
        libraryExport: "default",
    },
    resolve: {
        extensions: [".ts", ".js"],
    },
    plugins: [
        new webpack.SourceMapDevToolPlugin({
            filename: null,
            test: /\.(ts|js)($|\?)/i,
        }),
    ],
    module: {
        rules: [
            {
                test: require.resolve("jquery-migrate"),
                use: "imports-loader?define=>false",
            },
            {
                loader: "ts-loader",
                test: /\.ts$/,
                exclude: /node_modules/,
                options: {
                    compilerOptions: {
                        declaration: false,
                    },
                },
            },
            {
                loader: "istanbul-instrumenter-loader",
                enforce: "post",
                test: /\.ts$/,
                exclude: /(node_modules|\.spec\.ts$)/,
                options: {
                    esModules: true,
                },
            },
        ],
    },
};
```

But to your question @dmethvin we are using webpack 3.6.0 with node 5.6.0.

**Comment by dmethvin** [comment] 2017-09-27 13:51
@ldrick Thanks! I was just looking that up myself. The key is this part:
```js
            {
                test: require.resolve("jquery-migrate"),
                use: "imports-loader?define=>false",
            },
```
It's mentioned as a resolution in [bullet 4 in this answer](https://stackoverflow.com/questions/28969861/managing-jquery-plugin-dependency-in-webpack).

**Comment by dmethvin** [comment] 2017-09-27 14:06
Some background about this, it's basically Webpack creating an AMD loader that doesn't completely quack like one:
https://github.com/webpack/webpack/issues/4465

It seems one option is to fully disable AMD in Webpack if you don't need it, which will let Migrate follow the CommonJS path and then it works. See this ticket:
https://github.com/webpack/webpack/issues/3017#issuecomment-285954512

Now the question is, does it make sense to revert AMD support, publish 3.0.2, then re-commit AMD support and publish a 3.1.0 that will *still* break anyone using `~` or `>` in their package.json? Or is it sufficient for people to see the solution in this ticket?

**Comment by dmethvin** [comment] 2017-09-27 15:52
Another possibility is to favor CommonJS over AMD in the wrapper but that's yet another untested scenario to release into the wild.

**Comment by k-funk** [comment] 2017-09-27 23:17
**package.json**: `{ ... "jquery-migrate": "^3.0.0" ... }`

Am not doing anything special in my webpack config for migrate. **webpack config**:
```
...
{
      test: /\.js/,
      loader: 'babel-loader',
      exclude: /node_modules/,
      query: {
        presets: [
          ['es2015', { loose: true, modules: false }],
          'stage-2',
        ],
      },
    }
...
```

Importing migrate with `import 'jquery-migrate';` in one of my scripts that loads in-browser.

**Comment by dmethvin** [comment] 2017-09-28 02:05
@k-funk Can you try one of the solutions mentioned in the thread here to see if they work for you with 3.0.1? Either [use the imports-loader disabling `define`]](https://github.com/jquery/jquery-migrate/issues/273#issuecomment-332527584) or [disable AMD](https://github.com/webpack/webpack/issues/3017#issuecomment-285954512).

**Comment by m7moud** [comment] 2017-09-28 08:30
@dmethvin: Solutions work, even the simplest solution to depend exclusively on v3.0.0, but a normal deployment script with a step like `npm install` in any project that uses this package is now broken.

This change should have never been in a minor version, because it's not compatible and I guess it's also not a minor change.

**Comment by mgol** [comment] 2017-09-28 09:46
@m7moud It wasn't appropriate for a patch since it was a new feature but technically I think it's not been a breaking change. The break happens because of reliance of various Webpack configs over the properties of the `jquery-migrate.js` file that were never guaranteed.

**Comment by dmethvin** [comment] 2017-09-28 12:53
Yes, this is *not* a semver-major change. That is why I was [asking](https://github.com/jquery/jquery-migrate/issues/273#issuecomment-332532398) about whether it's worth the effort to issue a 3.0.2 without it and immediately a 3.1.0 with it. Many of the people on this thread will still need to change their webpack config for that case if they have `^3.0.0` in their package.json file. 

The module loader prologue added to Migrate is the exact same one used for jQuery itself since 2012 and is used by [other libraries like Lodash](https://github.com/webpack/webpack/issues/3017#issuecomment-285898454). As @mgol says, this is an issue with Webpack configs. We can't control those but I hope we've given enough options for fixing the situation.

**Comment by k-funk** [comment] 2017-09-28 19:22
Disabling `define` with `imports-loader` worked for me.

FWIW, I'm pinning to 3.0.0 until further release rather than cluttering my webpack config.

**Comment by mgol** [comment] 2017-09-28 19:26
> FWIW, I'm pinning to 3.0.0 until further release rather than cluttering my webpack config.

I think we're currently leaning to not changing anything in Migrate so you'll need to change the config at one point.

**Comment by dmethvin** [comment] 2017-10-12 22:21
It seems like that although this would have been better done in a semver-minor release, that wouldn't have made a lot of difference as far as breakage so I think we will leave this as it is.

**Closed by dmethvin** 2017-10-12 22:21 UTC

**Comment by cosmoKenney** [comment] 2019-01-23 21:17
So how do i fix this?

**Comment by dmethvin** [comment] 2019-01-23 22:07
https://github.com/jquery/jquery-migrate/issues/273#issuecomment-332527584

**Comment by mgol** [comment] 2019-01-23 22:31
@dmethvin Should we add it to README?

>

**Comment by cosmoKenney** [comment] 2019-01-25 17:04
The fix didn't have any effect for me. So I'm going to just pull the jquery-migrate out of the project and fix any issues that come up.

**Comment by mgol** [comment] 2019-01-25 17:17
@cosmoKenney You could also disable AMD compilation completely in Webpack if none of your dependencies depends on that, as explained in https://github.com/webpack/webpack/issues/3017. The `parser: {amd: false}` part is the key.
