### ISSUE TITLE
"json" 204 response causes migrate warning

### ISSUE THREAD

**Issue by hitsthings** [jquery/jquery-migrate#83] opened 2015-01-27 04:50 UTC
Not sure if this is a migrate issue or a core issue really. Migrate is logging when it shouldn't, but ideally core would never be calling it.

You write code like this:

```js
$.ajax({
    type: 'GET',
    url : 'http://demo0427801.mockable.io/no-content',
    dataType : 'json',
    async: true,
    statusCode : {
        204 : function() { console.log('made it') }
    }
})
```

Core works perfectly fine at the end of the day - reports all the right successes. However, along the way it calls `parseJSON` with an empty response string, then catches the error. catching the error isn't enough for the migrate plugin, which has already logged and `console.trace()`'d the issue.

JS Bin for this is here: http://jsbin.com/zixuciruxa/1/edit?html,js,console

**Comment by dmethvin** [comment] 2015-01-27 15:01
It's definitely an edge case, since the return value is not valid JSON but the type indicates it should be. The good news is that it's just a warning. I'll leave this open so it can be investigated (further info welcome!) but having the warning is okay with me.

**Comment by hitsthings** [comment] 2015-01-27 23:32
Yeah the thing that makes it less edge case is that there's no way to get this to work for an endpoint that returns JSON on 200, but also returns 204s with no content depending on server state. It's a legitimate use case.

The more I think about it, the more I think it's really an issue with the code in core for attempting to parseJSON on an empty string (that _should_ be empty).

At any rate, we can work around it a couple different ways:

1. turn off warnings / switch to minified migrate plugin (we currently minify everything ourselves in bulk)
2. Remove the "json" dataType and manually `JSON.parse` on a 200.

It's just annoying to have the log spam is all.

Cheers!

**Comment by brandonhall** [comment] 2015-04-24 14:37
We've run into this same issue with `$.parseJSON`. A significant portion of our `DELETE` calls return a 204. Currently, it's the only issue we have after the jQuery upgrade. Is it safe to remove the migrate plugin if this is the only warning we are getting?

**Comment by dmethvin** [comment] 2015-04-24 15:14
@brandonhall It's hard to say without knowing the exact code and server response. If you remove Migrate and your DELETE requests don't throw errors, then you wouldn't need Migrate for this situation. If the server correctly returned `Content-type: application/json` for 200 JSON responses and either no type or something like `Content-type: text/plain` for 204 empty responses, then you could just remove the `datatype:  "json"` from the call. Or the server can continue to return a JSON content type and just return a valid JSON response such as `{}` instead of nothing.

The problem with the case @hitsthings reported is that the contract `$.ajax()` gives the user says the first argument of the `success` callback is "the data returned from the server, formatted according to the dataType parameter ." It does not go on to say, "If the server sometimes gives you some other content type, or no content at all, we'll  return that as the first argument even though we can't convert it to the data type you requested." As you can imagine that leads to really hard-to-find bugs, which is why this behavior was changed in 1.9.

**Comment by brandonhall** [comment] 2015-04-24 16:56
@dmethvin Thank you so much for the detailed answer

**Comment by dmethvin** [comment] 2015-07-16 01:09
I'm going to close this since it's only a warning and since it's really working as intended.

> The more I think about it, the more I think it's really an issue with the code in core for attempting to parseJSON on an empty string (that should be empty).

If the `$.ajax` caller forces `dataType: "json"` then the server must return valid JSON or we can't honor the API contract. I've mentioned the other ways to handle this above, either let the server dictate the data type or have the server consistently return valid JSON.

**Closed by dmethvin** 2015-07-16 01:09 UTC
