### ISSUE TITLE
PhantomJS is blocking tests to run

### ISSUE THREAD

**Issue by mgol** [jquery/jquery-migrate#237] opened 2016-11-02 22:58 UTC
```
$ grunt test
Running "qunit:files" (qunit) task
Testing test/index.html 
PhantomJS threw an error:ERROR
>> 0 [ '' ]
Warning: PhantomJS exited unexpectedly with exit code null. Use --force to continue.

Aborted due to warnings.
```

See https://github.com/qunitjs/qunit/issues/1048 for a related QUnit issue.

I suspect our tests on TestSwarm work mostly because of the local `node_modules` cache...

The [grunt-qunit-istanbul](https://github.com/asciidisco/grunt-qunit-istanbul) fork is also blocking us from upgrading Grunt to version 1.x.

**Comment by dmethvin** [comment] 2017-07-20 19:42
I think I got most of this fixed with the PhantomJS upgrade earlier this week. I still haven't seen test coverage reports from coveralls because of the spurious Edge 15 error on Testswarm that I can't reproduce on my local Edge 15. However, I have a PR for the failing test to do some unrelated changes and maybe that will kick it to do the right thing.

**Closed by dmethvin** 2017-07-20 19:42 UTC
